version: "1.0"
build:
  android:
    environment:
      JAVA_VERSION: "17"
      JAVA_HOME: "/opt/jdk-17"
      PATH: "${JAVA_HOME}/bin:${PATH}"
    steps:
      - run: npm ci --quiet || npm install --quiet --legacy-peer-deps
      - run: echo "org.gradle.java.home=/opt/jdk-17" >> android/gradle.properties
